from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(633, 317)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.352318, y1:0.329, x2:0.04, y2:0.023, stop:0 rgba(95, 113, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_main = QtWidgets.QPushButton(self.centralwidget)
        self.button_main.setGeometry(QtCore.QRect(10, 10, 211, 101))
        self.button_main.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_main.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));\n"
"font: 22pt \"MS Sans Serif\";\n"
"")
        self.button_main.setAutoDefault(False)
        self.button_main.setDefault(False)
        self.button_main.setFlat(False)
        self.button_main.setObjectName("button_main")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(410, 0, 221, 271))
        self.scrollArea.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.scrollArea.setMouseTracking(False)
        self.scrollArea.setTabletTracking(False)
        self.scrollArea.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.scrollArea.setAcceptDrops(False)
        self.scrollArea.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.352318, y1:0.329, x2:0.04, y2:0.023, stop:0 rgba(95, 113, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 201, 489))
        self.scrollAreaWidgetContents.setMouseTracking(False)
        self.scrollAreaWidgetContents.setInputMethodHints(QtCore.Qt.ImhNone)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.progressBar_1 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_1.setGeometry(QtCore.QRect(10, 0, 191, 23))
        self.progressBar_1.setMaximum(50)
        self.progressBar_1.setProperty("value", 0)
        self.progressBar_1.setTextVisible(True)
        self.progressBar_1.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_1.setInvertedAppearance(False)
        self.progressBar_1.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_1.setObjectName("progressBar_1")
        self.pushButton_1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_1.setGeometry(QtCore.QRect(10, 30, 191, 23))
        self.pushButton_1.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.pushButton_1.setAutoDefault(False)
        self.pushButton_1.setDefault(False)
        self.pushButton_1.setFlat(False)
        self.pushButton_1.setObjectName("pushButton_1")
        self.progressBar_2 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_2.setGeometry(QtCore.QRect(10, 60, 191, 23))
        self.progressBar_2.setMaximum(200)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 90, 191, 23))
        self.pushButton_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.pushButton_2.setObjectName("pushButton_2")
        self.progressBar_3 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_3.setGeometry(QtCore.QRect(10, 120, 191, 23))
        self.progressBar_3.setMaximum(500)
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setTextVisible(True)
        self.progressBar_3.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_3.setInvertedAppearance(False)
        self.progressBar_3.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_3.setObjectName("progressBar_3")
        self.progressBar_4 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_4.setGeometry(QtCore.QRect(10, 180, 191, 23))
        self.progressBar_4.setMaximum(3000)
        self.progressBar_4.setProperty("value", 0)
        self.progressBar_4.setTextVisible(True)
        self.progressBar_4.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_4.setInvertedAppearance(False)
        self.progressBar_4.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_4.setObjectName("progressBar_4")
        self.progressBar_5 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_5.setGeometry(QtCore.QRect(10, 240, 191, 23))
        self.progressBar_5.setMaximum(6000)
        self.progressBar_5.setProperty("value", 0)
        self.progressBar_5.setTextVisible(True)
        self.progressBar_5.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_5.setInvertedAppearance(False)
        self.progressBar_5.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_5.setObjectName("progressBar_5")
        self.progressBar_6 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_6.setGeometry(QtCore.QRect(10, 300, 191, 23))
        self.progressBar_6.setProperty("value", 0)
        self.progressBar_6.setTextVisible(True)
        self.progressBar_6.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_6.setInvertedAppearance(False)
        self.progressBar_6.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_6.setObjectName("progressBar_6")
        self.progressBar_7 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_7.setGeometry(QtCore.QRect(10, 360, 191, 23))
        self.progressBar_7.setProperty("value", 0)
        self.progressBar_7.setTextVisible(True)
        self.progressBar_7.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_7.setInvertedAppearance(False)
        self.progressBar_7.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_7.setObjectName("progressBar_7")
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 150, 191, 23))
        self.pushButton_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 210, 191, 23))
        self.pushButton_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 270, 191, 23))
        self.pushButton_5.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 330, 191, 23))
        self.pushButton_6.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 390, 191, 23))
        self.pushButton_7.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 422, 81, 61))
        self.pushButton_8.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.pushButton_8.setObjectName("pushButton_8")
        self.lcd_main_3 = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.lcd_main_3.setGeometry(QtCore.QRect(100, 420, 101, 61))
        self.lcd_main_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.lcd_main_3.setSmallDecimalPoint(False)
        self.lcd_main_3.setObjectName("lcd_main_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.progressBar_level = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_level.setGeometry(QtCore.QRect(230, 60, 171, 41))
        self.progressBar_level.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.progressBar_level.setMaximum(200)
        self.progressBar_level.setProperty("value", 0)
        self.progressBar_level.setObjectName("progressBar_level")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(340, 10, 61, 41))
        self.lineEdit.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.lineEdit.setObjectName("lineEdit")
        self.lcd_main = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_main.setGeometry(QtCore.QRect(10, 170, 391, 101))
        self.lcd_main.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.lcd_main.setSmallDecimalPoint(False)
        self.lcd_main.setObjectName("lcd_main")
        self.lcd_main_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_main_2.setGeometry(QtCore.QRect(230, 10, 101, 41))
        self.lcd_main_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.lcd_main_2.setSmallDecimalPoint(False)
        self.lcd_main_2.setObjectName("lcd_main_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 120, 391, 41))
        self.lineEdit_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.lineEdit_2.setObjectName("lineEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 633, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Вк кликер"))
        self.button_main.setText(_translate("MainWindow", "Пост!"))
        self.progressBar_1.setFormat(_translate("MainWindow", "%p%"))
        self.pushButton_1.setText(_translate("MainWindow", "Нанять Администраторов"))
        self.pushButton_2.setText(_translate("MainWindow", "Заказать Чат-Ботов"))
        self.progressBar_3.setFormat(_translate("MainWindow", "%p%"))
        self.progressBar_4.setFormat(_translate("MainWindow", "%p%"))
        self.progressBar_5.setFormat(_translate("MainWindow", "%p%"))
        self.progressBar_6.setFormat(_translate("MainWindow", "%p%"))
        self.progressBar_7.setFormat(_translate("MainWindow", "%p%"))
        self.pushButton_3.setText(_translate("MainWindow", "Улучшить дизайн группы "))
        self.pushButton_4.setText(_translate("MainWindow", "Улучшить качество контента"))
        self.pushButton_5.setText(_translate("MainWindow", "Реклама в сторонних источниках"))
        self.pushButton_6.setText(_translate("MainWindow", "Нанять проффесиональных админов"))
        self.pushButton_7.setText(_translate("MainWindow", "Основать новую группу(перзапуск)"))
        self.pushButton_8.setText(_translate("MainWindow", "Множитель"))
        self.lineEdit.setText(_translate("MainWindow", "Уровень"))
        self.lineEdit_2.setText(_translate("MainWindow", "Начинайте кликать на кнопку \'Пост\'!"))
