from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(644, 356)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.352318, y1:0.329, x2:0.04, y2:0.023, stop:0 rgba(95, 113, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_main = QtWidgets.QPushButton(self.centralwidget)
        self.button_main.setGeometry(QtCore.QRect(10, 10, 211, 131))
        self.button_main.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_main.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));\n"
"font: 22pt \"MS Sans Serif\";\n"
"")
        self.button_main.setAutoDefault(False)
        self.button_main.setDefault(False)
        self.button_main.setFlat(False)
        self.button_main.setObjectName("button_main")
        self.progressBar_level = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_level.setGeometry(QtCore.QRect(230, 100, 171, 41))
        self.progressBar_level.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.progressBar_level.setMaximum(200)
        self.progressBar_level.setProperty("value", 0)
        self.progressBar_level.setObjectName("progressBar_level")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(340, 50, 61, 41))
        self.lineEdit.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.lineEdit.setObjectName("lineEdit")
        self.lcd_main = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_main.setGeometry(QtCore.QRect(10, 200, 391, 111))
        self.lcd_main.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.lcd_main.setSmallDecimalPoint(False)
        self.lcd_main.setObjectName("lcd_main")
        self.lcd_main_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_main_2.setGeometry(QtCore.QRect(230, 50, 101, 41))
        self.lcd_main_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.lcd_main_2.setSmallDecimalPoint(False)
        self.lcd_main_2.setObjectName("lcd_main_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 150, 391, 41))
        self.lineEdit_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(230, 10, 171, 31))
        self.lineEdit_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(410, 0, 231, 311))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 221, 281))
        self.scrollArea.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.scrollArea.setMouseTracking(False)
        self.scrollArea.setTabletTracking(False)
        self.scrollArea.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.scrollArea.setAcceptDrops(False)
        self.scrollArea.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.352318, y1:0.329, x2:0.04, y2:0.023, stop:0 rgba(95, 113, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 201, 599))
        self.scrollAreaWidgetContents.setMouseTracking(False)
        self.scrollAreaWidgetContents.setInputMethodHints(QtCore.Qt.ImhNone)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.progressBar_1 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_1.setGeometry(QtCore.QRect(10, 50, 191, 23))
        self.progressBar_1.setMaximum(50)
        self.progressBar_1.setProperty("value", 0)
        self.progressBar_1.setTextVisible(True)
        self.progressBar_1.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_1.setInvertedAppearance(False)
        self.progressBar_1.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_1.setObjectName("progressBar_1")
        self.pushButton_1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_1.setGeometry(QtCore.QRect(10, 80, 191, 23))
        self.pushButton_1.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.pushButton_1.setAutoDefault(False)
        self.pushButton_1.setDefault(False)
        self.pushButton_1.setFlat(False)
        self.pushButton_1.setObjectName("pushButton_1")
        self.progressBar_2 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_2.setGeometry(QtCore.QRect(10, 110, 191, 23))
        self.progressBar_2.setMaximum(200)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 140, 191, 23))
        self.pushButton_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.pushButton_2.setObjectName("pushButton_2")
        self.progressBar_3 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_3.setGeometry(QtCore.QRect(10, 170, 191, 23))
        self.progressBar_3.setMaximum(500)
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setTextVisible(True)
        self.progressBar_3.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_3.setInvertedAppearance(False)
        self.progressBar_3.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_3.setObjectName("progressBar_3")
        self.progressBar_4 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_4.setGeometry(QtCore.QRect(10, 230, 191, 23))
        self.progressBar_4.setMaximum(3000)
        self.progressBar_4.setProperty("value", 0)
        self.progressBar_4.setTextVisible(True)
        self.progressBar_4.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_4.setInvertedAppearance(False)
        self.progressBar_4.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_4.setObjectName("progressBar_4")
        self.progressBar_5 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_5.setGeometry(QtCore.QRect(10, 290, 191, 23))
        self.progressBar_5.setMaximum(6000)
        self.progressBar_5.setProperty("value", 0)
        self.progressBar_5.setTextVisible(True)
        self.progressBar_5.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_5.setInvertedAppearance(False)
        self.progressBar_5.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_5.setObjectName("progressBar_5")
        self.progressBar_6 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_6.setGeometry(QtCore.QRect(10, 350, 191, 23))
        self.progressBar_6.setMaximum(10000)
        self.progressBar_6.setProperty("value", 0)
        self.progressBar_6.setTextVisible(True)
        self.progressBar_6.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_6.setInvertedAppearance(False)
        self.progressBar_6.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_6.setObjectName("progressBar_6")
        self.progressBar_7 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_7.setGeometry(QtCore.QRect(10, 470, 191, 23))
        self.progressBar_7.setMaximum(40000)
        self.progressBar_7.setProperty("value", 0)
        self.progressBar_7.setTextVisible(True)
        self.progressBar_7.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_7.setInvertedAppearance(False)
        self.progressBar_7.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_7.setObjectName("progressBar_7")
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 200, 191, 23))
        self.pushButton_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 260, 191, 23))
        self.pushButton_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 320, 191, 23))
        self.pushButton_5.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 380, 191, 23))
        self.pushButton_6.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 500, 191, 23))
        self.pushButton_7.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 530, 81, 61))
        self.pushButton_8.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.pushButton_8.setObjectName("pushButton_8")
        self.lcd_main_3 = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        self.lcd_main_3.setGeometry(QtCore.QRect(100, 530, 101, 61))
        self.lcd_main_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.lcd_main_3.setSmallDecimalPoint(False)
        self.lcd_main_3.setObjectName("lcd_main_3")
        self.progressBar_8 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar_8.setGeometry(QtCore.QRect(10, 410, 191, 23))
        self.progressBar_8.setMaximum(20000)
        self.progressBar_8.setProperty("value", 0)
        self.progressBar_8.setTextVisible(True)
        self.progressBar_8.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_8.setInvertedAppearance(False)
        self.progressBar_8.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_8.setObjectName("progressBar_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 440, 191, 23))
        self.pushButton_9.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.pushButton_9.setObjectName("pushButton_9")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 9, 191, 31))
        self.lineEdit_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 10, 201, 31))
        self.lineEdit_5.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 211, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_10 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_10.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_11.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_12.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout.addWidget(self.pushButton_12)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 170, 210, 111))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_13 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_13.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_2.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_14.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_2.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_15.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255));")
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_2.addWidget(self.pushButton_15)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 644, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Вк кликер"))
        self.button_main.setText(_translate("MainWindow", "Тап!"))
        self.lineEdit.setText(_translate("MainWindow", "Уровень"))
        self.lineEdit_2.setText(_translate("MainWindow", "Начинайте кликать на кнопку \'Пост\'!"))
        self.progressBar_1.setFormat(_translate("MainWindow", "%p%"))
        self.pushButton_1.setText(_translate("MainWindow", "Нанять Администраторов"))
        self.pushButton_2.setText(_translate("MainWindow", "Заказать рекламу"))
        self.progressBar_3.setFormat(_translate("MainWindow", "%p%"))
        self.progressBar_4.setFormat(_translate("MainWindow", "%p%"))
        self.progressBar_5.setFormat(_translate("MainWindow", "%p%"))
        self.progressBar_6.setFormat(_translate("MainWindow", "%p%"))
        self.progressBar_7.setFormat(_translate("MainWindow", "%p%"))
        self.pushButton_3.setText(_translate("MainWindow", "Улучшить дизайн группы "))
        self.pushButton_4.setText(_translate("MainWindow", "Нанять проффесиональных админов"))
        self.pushButton_5.setText(_translate("MainWindow", "Реклама в сторонних источниках"))
        self.pushButton_6.setText(_translate("MainWindow", "Улучшить качество контента"))
        self.pushButton_7.setText(_translate("MainWindow", "Основать новую группу(перзапуск)"))
        self.pushButton_8.setText(_translate("MainWindow", "Множитель"))
        self.progressBar_8.setFormat(_translate("MainWindow", "%p%"))
        self.pushButton_9.setText(_translate("MainWindow", "Прислушаться к подписчикам"))
        self.lineEdit_4.setText(_translate("MainWindow", "Здесь вы можете улучшать ваш тап"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.lineEdit_5.setText(_translate("MainWindow", "Здесь вы можете выбрать тип группы"))
        self.pushButton_10.setText(_translate("MainWindow", "Группа с мемами"))
        self.pushButton_11.setText(_translate("MainWindow", "Научный контент"))
        self.pushButton_12.setText(_translate("MainWindow", "Тематическое сообщество(хардкор)"))
        self.pushButton_13.setText(_translate("MainWindow", "Сообщество"))
        self.pushButton_14.setText(_translate("MainWindow", "Публичная страница без комментариев"))
        self.pushButton_15.setText(_translate("MainWindow", "Публичная страница с комментариями"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))

